# -*- coding: utf-8 -*-
{
    'name': 'delivery_module',
    'version': '1.0',
    'summary': 'Delivery management enhancements',
    'description': 'Delivery management module with scheduling and driver features',
    'author': 'tofta',
    'category': 'Operations/Inventory',
    'depends': ['base', 'mail', 'web', 'stock'],
    'data': [
        'security/delivery_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/delivery_data.xml',
        'data/setup_delivery_schedule_data.xml',
        'views/action_views.xml',
        'views/menu_views.xml',
        'views/delivery_views.xml',
        'views/delivery_day_views.xml',
        'views/delivery_vehicle_views.xml',
        'views/res_city_views.xml',
        'views/res_city_district_views.xml',
        'views/res_partner_views.xml',
        'wizard/delivery_create_wizard_views.xml',
        'wizard/delivery_photo_wizard_views.xml',
        'wizard/cancel_confirmation_wizard_views.xml',
        'wizard/delivery_day_closure_wizard_views.xml',
        'wizard/delivery_vehicle_closure_wizard_views.xml',
        'wizard/delivery_limit_warning_wizard_views.xml',
        'wizard/setup_delivery_schedule_wizard_views.xml',
        'wizard/delivery_location_update_wizard_views.xml',
        'wizard/delivery_route_info_wizard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'delivery_module/static/src/js/hide_edit_done.js',
        ],
    },
    'installable': True,
    'application': True,
} 